#!/bin/bash

##
# Runit run script for the renderd daemon
#

#`/sbin/setuser www-data` runs the given command as the user `www-data`.  If
# you omit that part, the command will be run as root.

# if running on Cloud Foundry
if [[ -v VCAP_APPLICATION]]
then
  sed -i "s|HOST=.*|HOST=$(echo $VCAP_APPLICATION | jq .uris[0] -r)|" /usr/local/etc/renderd.conf
  GIS_DATABASE=$(echo $VCAP_SERVICES | jq '.[] | select(.[].credentials.engine=="postgres") | .[].credentials.database' -r)
  GIS_HOST=$(echo $VCAP_SERVICES | jq '.[] | select(.[].credentials.engine=="postgres") | .[].credentials.hostname' -r)
  GIS_USER=$(echo $VCAP_SERVICES | jq '.[] | select(.[].credentials.engine=="postgres") | .[].credentials.username' -r)
  GIS_PASSWORD=$(echo $VCAP_SERVICES | jq '.[] | select(.[].credentials.engine=="postgres") | .[].credentials.password' -r)
fi

cat /tmp/openstreetmap-carto/project.mml | sed "s/    dbname: .*/    dbname: \"$GIS_DATABASE\"/" | sed "/dbname/a \    host: \"$GIS_HOST\"" | sed "/dbname/a \    user: \"$GIS_USER\"" | sed "/dbname/a \    password: \"$GIS_PASSWORD\"" > /tmp/openstreetmap-carto/project_new.mml
carto /tmp/openstreetmap-carto/project_new.mml > /tmp/openstreetmap-carto/mapnik.xml
exec /sbin/setuser www-data /usr/local/bin/renderd --config /usr/local/etc/renderd.conf --foreground yes
